---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: desktop-os
# description will be included in the image's metadata
description: This is my personal OS image for my thinkpad.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 44 # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # nonfree multimedia codecs & general cleanup
  - type: dnf
    install:
      packages:
        - adw-gtk3-theme
    remove:
      packages:
        - fedora-flathub-remote
        - fedora-third-party
        - fedora-workstation-repositories
        - firefox
        - firefox-langpacks
        - fuse
        - passim
        - fedora-chromium-config

  - type: dnf
    replace:
      - from-repo: fedora-multimedia
        skip-unavailable: true
        packages:
          - libva
          - libva-intel-media-driver
          - mesa-dri-drivers
          - mesa-filesystem
          - mesa-libEGL
          - mesa-libGL
          - mesa-libgbm
          - mesa-va-drivers
          - mesa-vulkan-drivers
          - old: ffmpeg-free
            new: ffmpeg
          - old: libavcodec-free
            new: libavcodec
          - old: libavdevice-free
            new: libavdevice
          - old: libavfilter-free
            new: libavfilter
          - old: libavformat-free
            new: libavformat
          - old: libavutil-free
            new: libavutil
          - old: libpostproc-free
            new: libpostproc
          - old: libswresample-free
            new: libswresample
          - old: libswscale-free
            new: libswscale

  - type: dnf
    replace:
      - from-repo: fedora-multimedia
        skip-unavailable: true
        packages:
          - old: ffmpeg-free
            new: ffmpeg
          - old: libavcodec-free
            new: libavcodec
          - old: libavdevice-free
            new: libavdevice
          - old: libavfilter-free
            new: libavfilter
          - old: libavformat-free
            new: libavformat
          - old: libavutil-free
            new: libavutil
          - old: libpostproc-free
            new: libpostproc
          - old: libswresample-free
            new: libswresample
          - old: libswscale-free
            new: libswscale


  - type: dnf
    repos:
      copr:
        - atim/starship
      files:
        - https://repo.librewolf.net/librewolf.repo
    install:
      packages:
        - starship
        - librewolf

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
