---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: desktop-os
description: This is my personal OS image for my thinkpad.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # IMAGE VERSION

# module configuration, executed in order
modules:

  - type: dnf
    repos:
      nonfree: negativo17
    install:
      packages:
        - noctalia
        - niri
        - tailscale # accessing homelab
        - syncthing # file syncing with homelab
        - adw-gtk3-theme # gtk theme
        - papirus-icon-theme # icon theme
        - imv
        - foot
        - cascadia-mono-nf-fonts # font for foot
        - fastfetch # essential for every terminal!
        - mpv
        - thunar
        - gvfs-mtp # MTP support for GVFS
        - thunar-volman # auto USB management for thunar
        - tumbler # thumbnail support for thunar
        - xdg-user-dirs # default folders
        - thunar-archive-plugin # archive plugin
        - xarchiver # archive manager
        - steam
        - wine # windows software support
        - wine-mono # windows software support
      exclude:
        - alacritty
        - waybar
        - fuzzel
        - swaylock
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: script
    scripts:
      - millenium.sh # steam theming
      - papirus-folders.sh # change default papirus folder theme
      - starship.sh # starship bash prompt

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: chezmoi
    repository: "https://github.com/marcusoosthuizen/dotfiles" # my dotfiles repo
    file-conflict-policy: replace # override changed files with those from the repo
    disable-update: true

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
