---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: desktop-os
description: This is my personal OS image for my thinkpad.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # IMAGE VERSION

# module configuration, executed in order
modules:

  # swayfx & noctalia
  - type: dnf
    repos:
      copr:
        - swayfx/swayfx
    install:
      packages:
        - swayfx
        - noctalia

  - type: dnf
    repos:
      copr:
        - atim/starship
      files:
        - https://repo.librewolf.net/librewolf.repo
    install:
      packages:
        - starship
        - cascadia-mono-nf-fonts # for foot & starship
        - adw-gtk3-theme # for gtk applications (obviously)
        - librewolf
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
